# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

# Just build .NET project when a source file or project file is changed


name: Verify

on:
  push:
    branches:
    - '**'
    paths:
    - '**.cs'
    - '**.csproj'
  pull_request:
    branches:
    - '**'
    paths:
    - '**.cs'
    - '**.csproj'

permissions:
  contents: read # access to check out code and install dependencies

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        cache: true
    - name: Restore dependencies
      run: dotnet restore --locked-mode
    - name: Build
      run: dotnet build --no-restore --configuration Release
